# Generated by Django 4.0.6 on 2022-11-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_signup_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
