# Generated by Django 4.0.6 on 2022-11-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
